#
# Copyright 2019-2022 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only
#

[workspace]
resolver = "2"
members = [
  "backend",
  "load_test",
  "common",
  "docker/bootstrap",
  "frontend",
  "metrics",
]

[workspace.package]
version = "141.0.0"
edition = "2024"

[profile.release]
debug = 1
panic = "abort"
lto = "fat"
codegen-units = 1

[workspace.dependencies]
# match the version used by libsignal
bincode = "1.3.3"
# all the libsignal packages should use the same tag
libsignal-core = { git = "https://github.com/signalapp/libsignal", tag = "v0.101.0" }
zkgroup = { git = "https://github.com/signalapp/libsignal", tag = "v0.101.0" }
crc = "3.4.0"
sha1 = "0.11.0"
sha2 = "0.11.0"
hmac = "0.13.0"
rand = "0.10.2"
hkdf = "0.13.0"
x25519-dalek = "3.0.0"
